submitting homework for CSS exercise.
betamore/fewd-css-exercise-1 pull request #45
Opened 2018-10-15 02:05 UTC by Rangermyke

2018-10-15 17:04 UTC, zac-heisey requested changes
Hey Michael, take a look at the requested changes and let me know if you have any questions. Thanks!

2018-10-15 17:04 UTC, zac-heisey commented on michael-le.html
> +      <li id="green">1994: The first work on style sheets started at CERN.</li>
Don't forget to make your date in this line of code **bold** and _italicized_

2018-10-15 17:04 UTC, zac-heisey commented on michael-le.html
> +      <li ><span class="dates">December 1996</span>: CSS was proposed as W3C standard:
Careful with your spacing between `<>` tags.

2018-10-15 17:04 UTC, zac-heisey commented on css/michael-le.css
> +ul > li {
Check out the updated task for using a `child selector` in this assignment, and update this CSS rule.

2018-10-15 22:03 UTC, Rangermyke commented
Hey Zac, I have commited and pushed all the requested changes.

2018-10-15 23:56 UTC, zac-heisey requested changes
All of your fixes are looking good! Just a small tweak to be made.

2018-10-15 23:56 UTC, zac-heisey commented on css/michael-le.css
> +  font-family: "roboto"
missing an ending `;` after this CSS declaration.

2018-10-16 14:59 UTC, zac-heisey approved these changes

2018-10-16 15:00 UTC, merged